# Generated by Django 3.1.2 on 2020-10-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0002_auto_20201020_1151'),
        ('inmueble', '0002_casa'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='inmobiliaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.inmobiliaria'),
        ),
    ]
