# Generated by Django 3.1.2 on 2020-10-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmobiliaria',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
